import { NavBar } from '../NavBar'
import Head from 'next/head'

import styles from './MainLayout.module.css'
import { FC } from 'react'

interface Props {
  title?: string;
  children?: JSX.Element | JSX.Element[];
}

export const MainLayout: FC<Props> = ({ children }) => {  //Para recibir y desestructurar nuestro functional Component debemos pasarle las Props para que pueda aceptar
  return (
    <div className={styles.container}>
    <Head>
      <title>App - Daniel </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <NavBar />

    <main className={styles.main}>
     {children}   
    </main>


  </div>
  )
}

